[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.9",
    "pyqt6>=6.9.1",
    "pyqt6-webengine>=6.9.0",
]
